version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: gasstation-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: gasstation
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  gasstation-app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/gasstation
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network

  nginx-balancer:
    image: nginx:alpine
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gasstation-app
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
